apiVersion: v1
kind: Pod
metadata:
  name: demo-kotlinapp
  labels:
    role: webapp
spec:
  containers:
    - name: web
      image: clecio/demo-kotlin2.0
      ports:
        - containerPort: 80
          name: web
          protocol: TCP
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"