name: Continuos Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show current directory and list files
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the current directory:"
          ls -al

      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: Gradle Build
        run: |
          gradle build

      - name: Verificar arquivos gerados pelo Gradle
        run: |
          ls -al build/libs

      - name: Docker version
        run: |
          docker --version
          docker images -a  

      - name: Docker Login
        run: echo "${{ secrets.dockerhubpassword }}" | docker login -u ${{ secrets.dockerhubusername }} --password-stdin

      - name: Docker image Tag
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Dockerfile -t ${{ secrets.dockerhubusername }}/demo-kotlin2.0:${IMAGE_TAG} .
          docker push ${{ secrets.dockerhubusername }}/demo-kotlin2.0:${IMAGE_TAG}
