name: Continuos Integration

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

  get-the-files:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: running a custom scrip
        run: |
          ls -al

      # - name: Log in with the Azure CLI
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - uses: azure/aks-set-context@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      #     cluster-name: githubactionsaks
      #     resource-group: githubRGACTION
      # - run: |
      #     kubectl create namespace githubrg
      # - run: |
      #     kubeclt apply -f pod.yaml

      # - name:  Run AZ Command
      #   run: |
      #     az account show
      #     az group list

  get-the-multilinetask:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        if: always()
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Check Java Version
        run: |
          java -version

      - name: Gradle Build
        run: |
          bash gradlew build

      - name: doccker version
        run: |
          docker --version
          docker
          docker images -a  

      - name: Docker Login
        run: echo "${{ secrets.dockerhubpassword }}" | docker login -u ${{ secrets.dockerhubusername }} --password-stdin

      - name: Docker image Tag
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.dockerhubusername }}/demo-kotlin2.0:${IMAGE_TAG} .
          docker push ${{ secrets.dockerhubusername }}/demo-kotlin2.0:${IMAGE_TAG}