name: Continuos Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show current directory and list files
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the current directory:"
          ls -al

      - name: Set permissions on Dockerfile
        run: |
          chmod +r Dockerfile

      - name: Verify Dockerfile location
        run: |
          echo "Checking if Dockerfile exists in root directory:"
          if [ -f $(pwd)/Dockerfile ]; then
            echo "Dockerfile found in the root directory."
          else
            echo "Dockerfile not found in the root directory."
            exit 1
          fi

      - name: Docker image Tag
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f $(pwd)/Dockerfile -t ${{ secrets.dockerhubusername }}/demo-kotlin2.0:${IMAGE_TAG} .
          docker push ${{ secrets.dockerhubusername }}/demo-kotlin2.0:${IMAGE_TAG}
