name: 'Terraform'

on:
  push:
    branches:
      - main

jobs:

  terraform:

    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Install pre reqs'
        run: |
          curl -SL "https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip" -o terraform.zip
          unzip terraform.zip
          mv terraform /usr/local/bin/
          terraform --version
          rm terraform.zip

      - name: 'Install TFLint'
        run: |
          wget https://github.com/terraform-linters/tflint/releases/download/v0.48.0/tflint_linux_amd64.zip
          unzip tflint_linux_amd64.zip
          mv tflint /usr/local/bin/
          tflint --version
          









