name: 'Terraform'

on:
  push:
    branches:
      - main

jobs:

  terraform:

    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    environment: production
    defaults:
      run:
        working-directory: ./terraform

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Install pre reqs'
        run: |
          curl -SL "https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip" -o terraform.zip
          rm -f /usr/local/bin/terraform # Remove any existing terraform binary in /usr/local/bin
          unzip -o terraform.zip -d /tmp # Extract to a temporary directory
          sudo mv /tmp/terraform /usr/local/bin/
          terraform --version
          rm -rf terraform.zip

      - name: 'Install TFLint'
        run: |
          wget https://github.com/terraform-linters/tflint/releases/download/v0.48.0/tflint_linux_amd64.zip
          unzip tflint_linux_amd64.zip
          mv tflint /usr/local/bin/
          tflint --version

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        run: terraform plan

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve











